using MassTransit;
using MessageExchangeModel;
using ProgressNotesAPI.Infrastructure;

namespace ProgressNotesAPI
{
    public class ObservationConsumer : IConsumer<Message>
    {
        ProgressNotesDbContext dBContext;
        public ObservationConsumer(ProgressNotesDbContext dBContext)
        {
            this.dBContext = dBContext;
        }
        public async Task Consume(ConsumeContext<Message> context)
        {
            await Console.Out.WriteLineAsync(context.Message.Description);

            dBContext.ProgressNotes.Add(new ProgressNote()
            {
                ObservationId = context.Message.ObservationId,
                CreateDateTime = DateTime.Now,
                Description = $"Generated by Observation with Description: {context.Message.Description}",
            });
            await dBContext.SaveChangesAsync();
        }
    }
}
